@port = 3000

###

### POST Request for a team

# @name postATeam
POST http://localhost:{{port}}/api/v1/teams HTTP/1.1
content-type: application/json

{
  "name": "Liverpool FC",
  "venue": "Anfield",
  "venueCapacity": 9000,
  "league": "English Premier League",
  "kitColour": "Red",
  "manager": "Jurgen Klopp"
}

###
### GET Request for a team
GET http://localhost:{{port}}/api/v1/teams HTTP/1.1

###
@newObjectID = {{postATeam.response.body._id}}

###
### GET request for a team by new ID
GET http://localhost:{{port}}/api/v1/teams/{{newObjectID}} HTTP/1.1

###
### PUT request for a team by new ID - (updates the latest team added)
PUT http://localhost:{{port}}/api/v1/teams/{{newObjectID}} HTTP/1.1
content-type: application/json

{
    
  "name": "Manchester City",
  "venue": "The Etihad",
  "venueCapacity": 53400,
  "league": "English Premier League",
  "kitColour": "Blue",
  "manager": "Pep Guardiola"
}

###
### DELETE request to delete the latest entry
DELETE http://localhost:{{port}}/api/v1/teams/{{newObjectID}} HTTP/1.1